# <% require "dotenv"; Dotenv.load(".env") %>

service: demo-ruby-rails-8-rc2
image: gambala/demo-ruby-rails-8-rc2
servers:
  - <%= ENV["MAIN_SERVER_IP"] %>
proxy:
  ssl: false
  host: rails-demo.gambala.pro
  app_port: 80
  healthcheck:
    interval: 10
    path: /up
registry:
  server: ghcr.io
  username: gambala
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    # SOLID_QUEUE_IN_PUMA: true
    # JOB_CONCURRENCY: 3
    RAILS_MAX_THREADS: 2
    WEB_CONCURRENCY: 1
    # DB_HOST: 192.168.0.2
    # RAILS_LOG_LEVEL: debug
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
volumes:
  - "demo-ruby-rails-8-rc2-storage:/rails/storage"
asset_path: /rails/public/assets
builder:
  arch: arm64
